always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
short_to_long_function_def = false
always_use_return = true
whitespace_in_kwargs = true
join_lines_based_on_source = true
